# Generated by Django 5.2.8 on 2025-11-15 17:50

import admin_panel.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0001_initial'),
        ('auroramart', '0002_product_image_product_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(default=admin_panel.models.generate_voucher_code, max_length=32, unique=True)),
                ('days_valid', models.PositiveIntegerField(default=30, help_text='How many days the voucher is valid from assignment')),
                ('percent_off', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cap_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='VoucherAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('used', models.BooleanField(default=False)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voucher_assignments', to='auroramart.customer')),
                ('voucher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='admin_panel.voucher')),
            ],
            options={
                'ordering': ('-assigned_at',),
                'unique_together': {('voucher', 'customer')},
            },
        ),
    ]
