# Generated by Django 5.2.8 on 2025-11-09 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommercemodule', '0002_rename_customerprofile_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='monthly_income_sgd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
    ]
