# Generated by Django 5.2.8 on 2025-11-12 11:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auroramart', '0002_product_image_product_image_url'),
        ('ecommercemodule', '0003_remove_review_title_alter_review_body_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, help_text="e.g., 'Home' or 'Work'", max_length=50)),
                ('recipient_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\+?\\d{8,15}$', 'Enter a valid phone number.')])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('postal_code', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator('^\\d{6}$', 'Enter a 6-digit Singapore postal code.')])),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_notes', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='auroramart.customer')),
            ],
            options={
                'verbose_name': 'Customer Address',
                'verbose_name_plural': 'Customer Addresses',
                'ordering': ['-is_default', '-updated_at'],
            },
        ),
    ]
