# Generated by Django 5.2.8 on 2025-11-15 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommercemodule', '0002_alter_order_status'),
        ('ecommercemodule', '0004_customeraddress'),
    ]

    operations = [
    ]
