# Generated by Django 5.2.8 on 2025-11-16 08:44

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommercemodule', '0005_merge_0002_alter_order_status_0004_customeraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='voucher_code',
            field=models.CharField(blank=True, help_text='Applied voucher code', max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='voucher_discount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Discount amount from voucher', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
