# Generated by Django 5.2.8 on 2025-11-11 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auroramart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload a product image file', null=True, upload_to='products/', verbose_name='Product Image'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, help_text='External image URL (e.g., from Google Images)', max_length=500, null=True, verbose_name='Image URL'),
        ),
    ]
